# Generated by Django 4.1.7 on 2023-02-21 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type_of_theme', models.CharField(choices=[('DARK', 'Dark'), ('LIGHT', 'Light')], default='DARK', max_length=7)),
            ],
        ),
    ]
