# Generated by Django 4.1.7 on 2023-03-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('type', models.CharField(choices=[('MOVIE', 'movie'), ('TV-SERIES', 'tv-series'), ('CARTOON', 'cartoon'), ('ANIME', 'anime'), ('ANIMATED-SERIES', 'animated-series'), ('TV-SHOW', 'tv-show')], max_length=15)),
                ('seasons_count', models.IntegerField(null=True)),
                ('series_count', models.IntegerField(null=True)),
            ],
        ),
    ]
