# Generated by Django 4.1.7 on 2023-03-03 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0004_series_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='series',
        ),
        migrations.AddField(
            model_name='series',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kinokino.season'),
        ),
    ]
