# Generated by Django 4.1.7 on 2023-03-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0005_remove_season_series_series_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='tv_series_id',
            new_name='tv_shows_id',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='tv_series_id',
            new_name='tv_shows_id',
        ),
    ]
