# Generated by Django 4.1.7 on 2023-03-03 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0006_rename_tv_series_id_season_tv_shows_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='tv_shows_id',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='tv_shows_id',
            new_name='movie_id',
        ),
    ]
