# Generated by Django 4.1.7 on 2023-03-03 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0007_rename_tv_shows_id_season_movie_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='movie_id',
        ),
    ]
