# Generated by Django 4.1.7 on 2023-03-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0009_movie_release_year_end_movie_release_year_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='season',
            name='number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='series',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='series',
            name='number',
            field=models.IntegerField(default=None),
        ),
    ]
