# Generated by Django 4.1.7 on 2023-03-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0010_movie_kinopoisk_id_movie_year_season_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('tv-series', 'tv-series'), ('cartoon', 'cartoon'), ('anime', 'anime'), ('animated-series', 'animated-series'), ('tv-show', 'tv-show')], default=None, max_length=15),
        ),
    ]
