# Generated by Django 4.1.7 on 2023-03-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0012_alter_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv-series', 'Tv-Series'), ('cartoon', 'Cartoon'), ('anime', 'Anime'), ('animated-series', 'Animated-Series'), ('tv-show', 'TV-Show')], default=None, max_length=15, null=True),
        ),
    ]
