# Generated by Django 4.1.7 on 2023-03-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0013_alter_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='episodes_count',
            field=models.IntegerField(default=None),
        ),
    ]
