# Generated by Django 4.1.7 on 2023-03-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0015_rename_series_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='series_count',
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year_start',
            field=models.IntegerField(null=True),
        ),
    ]
