# Generated by Django 4.1.7 on 2023-03-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0017_alter_episode_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Не смотрю', 'не смотрю'), ('Хочу посмотреть', 'хочу посмотреть'), ('Смотрю', 'смотрю'), ('Просмотрено', 'просмотрено')], default='Не смотрю', max_length=16),
        ),
    ]
