# Generated by Django 4.1.7 on 2023-03-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0021_movie_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
