# Generated by Django 4.1.7 on 2023-03-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0022_alter_episode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='complete',
            field=models.ManyToManyField(to='kinokino.userprofile'),
        ),
        migrations.CreateModel(
            name='MovieStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Не смотрю', 'не смотрю'), ('Хочу посмотреть', 'хочу посмотреть'), ('Смотрю', 'смотрю'), ('Просмотрено', 'просмотрено')], default='Не смотрю', max_length=16)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinokino.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinokino.userprofile')),
            ],
        ),
    ]
