# Generated by Django 4.1.7 on 2023-03-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0023_episode_complete_moviestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='complete',
        ),
        migrations.AddField(
            model_name='movie',
            name='episodes_count',
            field=models.IntegerField(null=True),
        ),
    ]
