# Generated by Django 4.1.7 on 2023-03-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0024_remove_episode_complete_movie_episodes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episodes_complete',
            field=models.IntegerField(max_length=models.IntegerField(null=True), null=True),
        ),
    ]
