# Generated by Django 4.1.7 on 2023-03-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0026_alter_movie_episodes_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
