# Generated by Django 4.1.7 on 2023-03-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0029_alter_episode_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviestatus',
            name='status',
            field=models.CharField(choices=[('Хочу посмотреть', 'хочу посмотреть'), ('Смотрю', 'смотрю'), ('Просмотрено', 'просмотрено')], default='Не смотрю', max_length=16),
        ),
    ]
