# Generated by Django 4.1.7 on 2023-03-04 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0031_alter_moviestatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviestatus',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kinokino.movie'),
        ),
        migrations.AlterField(
            model_name='moviestatus',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kinokino.userprofile'),
        ),
    ]
