# Generated by Django 4.1.7 on 2023-03-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0032_alter_moviestatus_movie_alter_moviestatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviestatus',
            name='status',
            field=models.CharField(choices=[('------', None), ('Запланировано', 'запланировано'), ('Смотрю', 'смотрю'), ('Просмотрено', 'просмотрено')], default=None, max_length=16),
        ),
    ]
