# Generated by Django 4.1.7 on 2023-03-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0033_alter_moviestatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviestatus',
            name='status',
            field=models.CharField(choices=[('Запланировано', 'запланировано'), ('Смотрю', 'смотрю'), ('Просмотрено', 'просмотрено')], default=None, max_length=16),
        ),
    ]
