# Generated by Django 4.1.7 on 2023-03-05 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0035_remove_movie_episodes_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ManyToManyField(to='kinokino.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinokino.userprofile')),
            ],
        ),
    ]
