# Generated by Django 4.1.7 on 2023-03-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0037_collection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='preview_url',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
