# Generated by Django 4.1.7 on 2023-03-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0038_movie_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='complete',
            field=models.ManyToManyField(to='kinokino.userprofile'),
        ),
    ]
