# Generated by Django 4.1.7 on 2023-03-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0040_season_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='complete',
        ),
        migrations.CreateModel(
            name='CompletedEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinokino.episode')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinokino.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinokino.userprofile')),
            ],
        ),
    ]
