# Generated by Django 4.1.7 on 2023-03-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0041_remove_episode_complete_completedepisodes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedEpisodes',
            new_name='CompletedEpisode',
        ),
    ]
