# Generated by Django 4.1.7 on 2023-06-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0043_remove_episode_date_remove_episode_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='episodes_released',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
