# Generated by Django 4.1.7 on 2023-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0046_movie_shikimori_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='next_episode_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='kinopoisk_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
