# Generated by Django 4.1.7 on 2023-07-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0047_movie_next_episode_date_alter_movie_kinopoisk_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='kinopoisk_id',
            new_name='kinopoisk',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='shikimori_id',
            new_name='shikimori',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
