# Generated by Django 4.1.7 on 2023-07-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0048_rename_kinopoisk_id_movie_kinopoisk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
