# Generated by Django 4.1.7 on 2023-07-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0049_remove_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='kinopoisk',
            new_name='kinopoisk_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='shikimori',
            new_name='shikimori_id',
        ),
    ]
