# Generated by Django 4.1.7 on 2023-07-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0050_rename_kinopoisk_movie_kinopoisk_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='shikimori_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
    ]
