# Generated by Django 4.1.7 on 2023-07-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0051_remove_movie_shikimori_id_remove_movie_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='next_episode_date',
        ),
    ]
