# Generated by Django 4.1.7 on 2023-07-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0052_remove_movie_next_episode_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type_of_search',
            field=models.CharField(choices=[('Kinopoisk', 'kinopoisk'), ('Shikimori', 'shikimori')], default='Kinopoisk', max_length=10),
        ),
        migrations.CreateModel(
            name='ShikimoriMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shikimori_id', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=80)),
                ('image', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('anons', 'anons'), ('ongoing', 'ongoing'), ('released', 'released')], default=None, max_length=9, null=True)),
                ('episodes', models.IntegerField(default=1)),
                ('episodes_aired', models.IntegerField(default=None, null=True)),
                ('aired_on', models.DateField()),
                ('next_episode_date', models.DateField(default=None, null=True)),
                ('released_on', models.DateField()),
                ('favorite', models.ManyToManyField(to='kinokino.userprofile')),
            ],
        ),
    ]
