# Generated by Django 4.1.7 on 2023-07-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinokino', '0053_userprofile_type_of_search_shikimorimovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedEpisodeShikimori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_complete_count', models.IntegerField(default=None, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinokino.shikimorimovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinokino.userprofile')),
            ],
        ),
    ]
